version: "3"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.0.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafkacat:
    image: confluentinc/cp-kafkacat:6.0.1
    command: "kafkacat -C -b kafka:9093 -q -t outbox -K:"
    tty: true
    depends_on:
      - kafka

  jdbc:
    image: juplo/data-jdbc:polling-outbox-2
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: prod
    depends_on:
      - postgres

  outbox:
    image: juplo/outbox-delivery:polling-outbox-2
    environment:
      spring.profiles.active: prod
      logging.level.de.juplo.kafka.outbox: DEBUG
    depends_on:
      - postgres
      - kafka


  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: outbox
      POSTGRES_PASSWORD: outbox
      POSTGRES_DB: outbox
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
