management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: production

  datasource:
    url: jdbc:postgres://postgres/outbox
    username: outbox
    password: outbox
